function loadCSS(e,a,t){"use strict";var r=window.document.createElement("link"),n=a||window.document.getElementsByTagName("script")[0];r.rel="stylesheet",r.href=e,r.media="only x",n.parentNode.insertBefore(r,n),setTimeout(function(){r.media=t||"all"})}window.addEventListener?window.addEventListener("load",downloadJSAtOnload,!1):window.attachEvent?window.attachEvent("onload",downloadJSAtOnload):window.onload=downloadJSAtOnload,loadCSS("//fonts.googleapis.com/css?family=Roboto+Condensed:400,700"),loadCSS("//fonts.googleapis.com/css?family=Oswald:400,700|Droid+Sans:400,700"),loadCSS("//fonts.googleapis.com/css?family=Titillium+Web:400,700");
// Menu - Don't Delete This
$(document).ready(function(){var str=location.href.toLowerCase();$("#menu-menu li a").each(function(){if (str.indexOf(this.href.toLowerCase()) > -1) {$("li.active").removeClass("active");$(this).parent().addClass("active");}});})
// Menu
$(function(){$(".menu-item").data("size","big")});$(window).scroll(function(){if($(document).scrollTop()>70){if($(".menu-item").data("size")=="big"){$(".menu-item").data("size","small");$("li.hg").stop().animate({width:"122px"},600);$(".menu-item").stop().animate({left:"10px"},600);$("li.hg img").fadeIn()}}else{if($(".menu-item").data("size")=="small"){$("li.hg img").fadeOut();$(".menu-item").data("size","big");$("li.hg").stop().animate({width:"0"},600);$(".menu-item").stop().animate({left:"0px"},600)}}})
$(document).ready(function() {$("#menu-nav a").attr({rel:"nofollow noopener"})});
// Backto top
$(function(){$(window).scroll(function(){$(this).scrollTop()>600?$(".backtotop").addClass("show"):$(".backtotop").removeClass("show")}),$(".backtotop").click(function(){return $("html,body").animate({scrollTop:0},600),!1})});
// Menu Sticky
var new_scroll_position=0;var last_scroll_position;var header=document.getElementById("menudesz");window.addEventListener("scroll",function(a){last_scroll_position=window.scrollY;if(new_scroll_position<last_scroll_position&&last_scroll_position>600){header.classList.remove("slideDown");header.classList.add("slideUp")}else{if(new_scroll_position>last_scroll_position){header.classList.remove("slideUp");header.classList.add("slideDown")}}new_scroll_position=last_scroll_position});
// Render KyunQIB
function KyunQIB(){for(var e=document.getElementsByClassName("img-kyunqib"),t=0;t<e.length;t++)isInViewport(e[t])&&(e[t].src=e[t].getAttribute("data-src"))}function isInViewport(e){var t=e.getBoundingClientRect();return t.bottom>=0&&t.right>=0&&t.top<=(window.innerHeight||document.documentElement.clientHeight)&&t.left<=(window.innerWidth||document.documentElement.clientWidth)}function registerListener(e,t){window.addEventListener?window.addEventListener(e,t):window.attachEvent("on"+e,t)}registerListener("load",KyunQIB),registerListener("scroll",KyunQIB);document.addEventListener("DOMContentLoaded",function(){"use strict";for(var e=document.querySelectorAll("a"),t=e.length,n=/firefox|trident/i.test(navigator.userAgent)?document.documentElement:document.body,o=function(e,t,n,o){return(e/=o/2)<1?n/2*e*e*e+t:n/2*((e-=2)*e*e+2)+t};t--;)e.item(t).addEventListener("click",function(e){var t,r=n.scrollTop,i=document.getElementById(/[^#]+$/.exec(this.href)[0]).getBoundingClientRect().top,c=n.scrollHeight-window.innerHeight,u=c>r+i?i:c-r,d=900,l=function(e){t=t||e;var i=e-t,c=o(i,r,u,d);n.scrollTop=c,d>i&&requestAnimationFrame(l)};requestAnimationFrame(l),e.preventDefault()})});
