// Streaming
setTimeout(function(){$("#myVideo").each(function(){$(this).replaceWith('<iframe class="video-xx loader" src="'+$(this).data("src")+'" allowfullscreen="allowfullscreen" height="410" width="727"></iframe>')})},5e3);
// Streaming fallback
var isAdsDisplayed = true;
// Onclick Notif
$('.post-body a').each(function () {var $this = $(this),href = $this.attr('href');$this.attr("onClick", "alert('Ka, jangan lupa kasih komentar ya, sebagai bentuk apresiasi dan penyemangat kami, juga supaya Blog Ini terlihat hidup =w=')");});
// Disqus Comment
var disqus_shortname="kyunqib";var disqus_url=disqus_blogger_current_url;(function(){var d=function(){var e=document.getElementById("comments");if(!e){e=document.getElementById("disqus-blogger-comment-block")}return e};var b=d();if(!!b){var c=document.createElement("div");c.id="disqus_thread";b.innerHTML="";b.appendChild(c);b.style.display="block";var a=document.createElement("script");a.async=!0;a.src="//"+disqus_shortname+".disqus.com/embed.js";(document.getElementsByTagName("head")[0]||document.body).appendChild(a)}})();!function(b,g,a){var d,f=b.getElementsByTagName(g)[0];b.getElementById(a)||(d=b.createElement(g),d.id=a,d.src="//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0",f.parentNode.insertBefore(d,f))}(document,"script","facebook-jssdk");var divs=["disqus-box","blogger-box","facebook-box"];var visibleDivId=null;function toggleVisibility(a){if(visibleDivId===a){visibleDivId=null}else{visibleDivId=a}hideNonVisibleDivs()}function hideNonVisibleDivs(){var b,a,c;for(b=0;b<divs.length;b++){a=divs[b];c=document.getElementById(a);if(visibleDivId===a){c.style.display="block"}else{c.style.display="none"}}}$(".commentbtn").click(function(a){$(this).addClass("btncurrent").siblings().removeClass("btncurrent")})
// View
document.getElementById("wtchz").appendChild(document.getElementById("wtchzz"));
// Related
function relatedposted_relz(C){document.write("<ul>");for(var P=0;P<itemz_relz;P++){var D,H=C.feed.entry[P],L=H.title.$t;if(P==C.feed.entry.length){break}for(var G=0;G<H.link.length;G++){if("replies"==H.link[G].rel&&"text/html"==H.link[G].type){var J=H.link[G].title,I=H.link[G].href}if("alternate"==H.link[G].rel){D=H.link[G].href;break}}var B;try{B=H.media$thumbnail.url}catch(M){s=H.content.$t,a=s.indexOf("<img"),b=s.indexOf('src="',a),c=s.indexOf('"',b+130),d=s.substr(b+130,c-b-130),B=-130!=a&&-130!=b&&-130!=c&&""!=d?d:"//2.bp.blogspot.com/-C3Mo0iKKiSw/VGdK808U7rI/AAAAAAAAAmI/W7Ae_dsEVAE/s1600-rw/no-thumb.png"}var F=H.published.$t,O=F.substring(0,4),N=F.substring(5,7),z=F.substring(8,10),x=new Array;if(x[1]="January",x[2]="February",x[3]="March",x[4]="April",x[5]="May",x[6]="June",x[7]="July",x[8]="August",x[9]="September",x[10]="October",x[11]="November",x[12]="December",document.write('<li><a href="'+D+'">'),1==image_relz&&document.write('<img class="img-kyunqib" alt="'+L+'" title="'+L+'" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="'+B+'"/>'),document.write('<h3 class="recent-post-title"><span>'+L+"</span></h3></a>"),"content" in H){var E=H.content.$t}else{if("summary" in H){var E=H.summary.$t}else{var E=""}}var K=/<\S[^>]*>/g;if(E=E.replace(K,""),1==summary_relz){if(E.length<summarychars_relz){document.write(E)}else{E=E.substring(0,summarychars_relz);var q=E.lastIndexOf(" ");E=E.substring(0,q),document.write(E+"...")}}var Q="",j=0;document.write('<div class="recent-posts-details"><span class="dett">'),1==dateitem_relz&&(Q=Q+x[parseInt(N,10)]+" "+z+" "+O,j=1),1==readmore_relz&&(1==j&&(Q+=" </span>"),Q=Q+'<span class="redmore"><a href="'+D+'" class="urls" target ="_top">Selengkapnya</a></span>',j=1),1==comment_relz&&(1==j&&(Q+=" <br> "),"1 Comments"==J&&(J="1 Comment"),"0 Comments"==J&&(J="No Comments"),J='<a href="'+I+'" target ="_top">'+J+"</a>",Q+=J,j=1),document.write(Q),document.write("</div>"),document.write("</li>")}document.write("</ul>")}$(document).ready(function(){$('#_rec-post ul li img').attr('data-src',function(i,src){return src.replace('s72-c','w175-h112-c')})})
